# Generated by Django 3.0rc1 on 2019-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
